/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData truck = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData features = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurance = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicalinsurance = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passengercommercial = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lcv = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposithand = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicleinsurance = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData constructionvehicle = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machinery = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifeinsurance = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twowheeler = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threewheeler = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mhcv = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData depositbag = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farmequipment = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generalinsurance = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privatecar = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debenture = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupee = IconData(0xf156, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
