/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData by_24_7 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accident = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debenture = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earthquake = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurance = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifeinsurance = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicalinsurance = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tipper = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_1 = IconData(0xf0d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupee = IconData(0xf156, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_moving = IconData(0xf4df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}